'use strict';

var _window = typeof unsafeWindow === 'undefined' ? window : unsafeWindow;

_window.JLISTS_GAMEJOURNOPROS =
{
    "name":            "GameJournoPros",
    "desc":            "Video-game journalists, PR execs, and editors",
    "source":          "http://www.breitbart.com/Breitbart-London/2014/09/21/GameJournoPros-we-reveal-every-journalist-on-the-list",
    "backgroundColor": "#740080",
    "borderColor":     "#0d9c00",
    "fontColor":       "#ffffff",
    "members":         [
        // the original list at time of exposure
        "Adam Rosenberg",
        "Alex Navarro",
        "Alex Rubens",
        "Alexa Ray Corriea",
        "Andrew Fitch",
        "Andrew Groen",
        "Andrew Hayward",
        "Andrew a Cunningham",
        "Andy Chalk",
        "Andy Eddy",
        "Annette Cardwell",
        "Anthony John Agnello",
        "Ben Kuchera",
        "Ben Gilbert",
        "Billy Shibley",
        "Brad Gallaway",
        "Bradley Shoemaker",
        "Brandon Cackowski-Schnell",
        "Brandon Justice",
        "Brandon Boyer",
        "Brian Leahy",
        "Britton Peele",
        "Casey Johnston",
        "Charles Husemann",
        "Chris Dahlen",
        "Chris Plante",
        "Christopher Grant",
        "Conrad Zimmerman",
        "Cory Banks",
        "Dale North",
        "Laura Dale",
        "Dalibor Dimovski",
        "Dan Stapleton",
        "Dan Crabtree",
        "Daniel Starkey",
        "Daniel Feit",
        "Danielle",
        "Davetach",
        "David Thomas",
        "Dead Yet Living",
        "Dean Takahashi",
        "Dennis Scimeca",
        "Devin Connors",
        "Devin Kofsky",
        "Dtroid Niero",
        "Erick Eckstein",
        "Erick Frederikesn",
        "Garnett Lee",
        "Garrett Martin",
        "George Wiedman",
        "Greg Tito",
        "Gregory Gay",
        "Harold Goldberg",
        "Heidi Kemps",
        "Issac Ferderspiel",
        "Jake Gaskill",
        "James Fudge",
        "Jarred Newman ",
        "Jason Fanelli",
        "Jason Leyanna",
        "Jason Schreier",
        "Jason Venter",
        "Jason Wilson",
        "Jaz Rignall ",
        "Jeffery Matulef",
        "Jeremy Zoss",
        "Joe Osborne",
        "John Funk",
        "Jonathan Deesing",
        "Jorge Jimenez",
        "Joseph Leray",
        "Josh Tolentino",
        "Julian Murdoch",
        "Justin McElroy",
        "Kate Cox",
        "Kevin Kelly",
        "Kyle Orland",
        "Kyle Horner",
        "Leah B. Jackson",
        "Logan Westbrook",
        "Lou Kesten",
        "Ludwig Kietzmann",
        "Maddy Myers",
        "Mark Burnham",
        "Matthew Kumar",
        "Matt Matthews",
        "Matthew Sakey",
        "Meghan",
        "Michael McWhertor",
        "Mike Futter",
        "Michael Rougeau",
        "Mike Wehner",
        "Mitch Dyer",
        "Chris Morris",
        "N'Gai Croal",
        "N. Evan Van Zelfden",
        "Nathan Grayson",
        "Nathan Meunier",
        "Nick Chester",
        "Phillip Kollar",
        "Pikoeri Egm",
        "Richard Mitchell",
        "Rob Zacny",
        "Rod Breslau",
        "Rollin Bishop",
        "Ron Whitaker",
        "RPad.TV",
        "Ryan Kuo",
        "Ryan Scott",
        "Ryanflemingpdx",
        "Sam Machovech",
        "Samit Sarkar",
        "Sarah LeBoeuf",
        "Scott Nichols",
        "Scott Steinberg",
        "Sebastian Haley",
        "Simon Ferrari",
        "Sinan Kubba",
        "Steven Kent",
        "Steve Haske",
        "Susan Arendt",
        "Taylor Cocke",
        "The Gamegoat",
        "Tim Stevens",
        "Timothy J. Seppala",
        "Tina Amini",
        "Tom Curtis",
        "Tom Chick",
        "Will Tuttle",
        "William Usher",
        "Max Parker",
        "Xav De Matos",
        "Yannick LeJacq",
        "Zack Stern",
        "Dan Hsu",

        // extras that left prior to exposure, src: https://twitter.com/WilliamUsherGB/status/529822860542750720
        "Leigh Alexander",
        "Patrick Klepek",
        "Matt Clark",
        "Russ Pitts"
    ]
};